version: '{build}'

skip_tags: true

install: []

environment:
  matrix:
    - VSVERSION: Visual Studio 9 2008
    - VSVERSION: Visual Studio 10 2010
    - VSVERSION: Visual Studio 11 2012
    - VSVERSION: Visual Studio 12 2013
    - VSVERSION: Visual Studio 14 2015
    - VSVERSION: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - VSVERSION: Visual Studio 16 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

platform:
  - Win32
  - x64

matrix:
  exclude:
    - platform: x64
      VSVERSION: Visual Studio 9 2008

configuration:
  - Debug
  - RelWithDebInfo
  - MinSizeRel
  - Release

build_script:
  - md build
  - cd build
  - if "%PLATFORM%"=="x64" set GENERATOR="%VSVERSION% Win64"
  - if "%PLATFORM%"=="Win32" set GENERATOR="%VSVERSION%"
  - if "%PLATFORM%"=="x64" set ARCHITECTURE="%VSVERSION% Win64"
  - if "%PLATFORM%"=="Win32" set ARCHITECTURE="%VSVERSION%"
  - if "%VSVERSION%"=="Visual Studio 16 2019" cmake -G "%GENERATOR%" -A "%ARCHITECTURE%" ../test
  - if NOT "%VSVERSION%"=="Visual Studio 16 2019" cmake -G "%GENERATOR%" ../test
  - cmake --build . --config %CONFIGURATION%
  - copy %CONFIGURATION%\utest_test.exe utest_test.exe

test_script:
  - utest_test.exe
